package de.syngenio.vaadin.synergy.layout;

import java.io.Serializable;

public interface SynergyLayoutFactory extends Serializable
{
    /**
     * @return a new instance of SynergyLayout
     */
    SynergyLayout generateLayout();
    
    /**
     * @return the LayoutFactory for the subitems
     */
    SynergyLayoutFactory getSubitemLayoutFactory();
    
    /**
     * Sets the style name for the SynergyLayouts generated by this factory
     * @param styleName the style name
     */
    void setStyleName(String styleName);

    /**
     * @return the style name to be set on the generated SynergyLayout
     */
    String generateStyleName();
}
